#http://localhost:8080/swagger-ui.html#!/upload-controller/uploadUsingPOST


server:
  port: 8080 # 访问端口
  tomcat:
    uri-encoding: utf-8
#  servlet:
#    context-path: /zq_blog  # 设置path

spring:
  # 连接mysql配置----------------------------------------------------------------------------------
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.237.100:3306/cloudFiles_database?useUnicode=true&characterEncoding=utf-8&useSSL=false  # 本地测试
    username: root
    password: 123456

mybatis-plus:  # Mybatis-Plus学习官方文档：https://baomidou.oschina.io/mybatis-plus-doc/#/quick-start
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.file.upload.entity

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

